### ISSUE TITLE
Hi Tiago

### ISSUE THREAD

**Issue by alltestgreen** [tiagomelo/harbor-service#2]
Thank you for taking the time to complete our test. Would you mind to help understand some approach related to your solution? I understand that some of the decisions are due to time constraint and keeping simplicity in mind. This is part of the interview process. 

- Regarding the docker file, all dependencies and files are bundled in one image. If it would be a production environment, how would you organise to run these?
- In the code, there are some functions that are solely to help unit testing, would be any way to get rid of those?
- `ApiMuxConfig` struct holds reference to a service and a logger. could you elaborate your decision here?
- Do you think anything could be extracted from main.go into a separate package/file?

**Comment by tiagomelo** [comment]
Hello, sure.

1. If this were a production system, I would:

- Separate the database, migration, and application containers.
- Use Docker Compose (or Kubernetes) to orchestrate them.

e.g., 

```
version: '3.9'

services:
  db:
    image: alpine:latest
    container_name: sqlite
    command: ["sh", "-c", "apk add --no-cache sqlite && tail -f /dev/null"]
    volumes:
      - sqlite_data:/root/storage/sqlite
    restart: always

  migrate:
    image: golang:1.24.0-alpine
    container_name: migrate
    depends_on:
      - db
    entrypoint: ["/usr/local/bin/migrate", "-database", "sqlite3:///root/storage/sqlite/harbor.db", "-path", "/root/storage/sqlite/migrations", "up"]
    volumes:
      - sqlite_data:/root/storage/sqlite
      - ./storage/sqlite/migrations:/root/storage/sqlite/migrations

  app:
    image: harbor-service:latest
    container_name: harbor-service
    depends_on:
      - db
      - migrate
    entrypoint: ["/harbor-service"]
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/root/storage/sqlite
    restart: always

volumes:
  sqlite_data:
    driver: local
```

2. I'm not sure to which functions you're referring to, but if they are these,

```
// For ease of unit testing.
var sqlOpen = sql.Open

...

// For ease of unit testing.
var (
	// newHttpResponseController is a function that creates a new response controller.
	newHttpResponseController = func(rw http.ResponseWriter) responseController {
		return http.NewResponseController(rw)
	}
)

...

// for ease of unit testing.
var (
	// marshalJson is a variable that holds the json.Marshal function.
	marshalJson = json.Marshal

	writeResponse = func(w http.ResponseWriter, response []byte) (int, error) {
		return w.Write(response)
	}
)

```

These functions are not solely for unit testing; they also improve flexibility and maintainability. Instead of introducing an external mocking dependency, we use function variables to allow controlled overrides in tests while keeping production behavior unchanged. This approach minimizes dependencies and makes the code easier to test without unnecessary abstractions. However, if there's a concern about readability, we can explore alternatives, such as dependency injection, but that might introduce additional complexity.

3. The `ApiMuxConfig` struct centralizes dependencies required by the API, making it easy to initialize and manage. The `HarborService` reference allows handlers to interact with business logic, while the `Logger` provides structured logging across requests. This approach improves maintainability by grouping related dependencies, making testing and future extensions more straightforward.

4. The current `main.go` follows a clean structure, keeping initialization, service wiring, and lifecycle management within a single entry point. However, if needed, we could extract `handleServerLifecycle` into a separate package (`internal/server` or `pkg/lifecycle`) to encapsulate server startup and shutdown concerns. Similarly, CLI parsing could be moved to a dedicated cmd package. That said, keeping these within `main.go` is a common and reasonable choice for a service of this size, maintaining readability without unnecessary abstraction.

Happy to answer any further questions you have!

Best,

Tiago
